### ISSUE TITLE
linux下项目可以启动，但是访问报错

### ISSUE THREAD

**Issue by ITZhai** [xiaour/SpringBootDemo#10]
2019-10-23 15:30:54.411 ERROR 25402 --- [nio-6688-exec-1] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing /test/index

java.lang.NullPointerException: null
 at org.apache.catalina.authenticator.AuthenticatorBase.getJaspicProvider(AuthenticatorBase.java:1192) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:465) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.

**Comment by xiaour** [comment]
其实如果在IDE中没有问题，整个打包放置到其他环境中也没有问题，毕竟Java是没有平台区分的，

经再次linux测试过没有问题，正常返回结果。你可以git pull 最新的代码重新打包。

你是最终打成war发布的吗？还是直接使用的jar启动？如果使用war可能会有javax-api的包冲突，在pom.xml中排除掉这个依赖即可。
