### ISSUE TITLE
mybatis绑定问题

### ISSUE THREAD

**Issue by boweiwu** [xiaour/SpringBootDemo#11]
项目导入后调用数据库查询出现以下错误
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.xiaour.spring.boot.mapper.UserInfoMapper.selectByPrimaryKey
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:225)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:48)
	at org.apache.ibatis.binding.MapperProxy.cachedMapperMethod(MapperProxy.java:65)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
	at com.sun.proxy.$Proxy88.selectByPrimaryKey(Unknown Source)

以检查过相关路径没有问题

**Comment by xiaour** [comment]
请使用 SpringBootDemoV2 项目，SpringBootDemo是Springboot 1.5.x 这个现在官方已经建议切换到2.x以上了
